# Dev specific values
replicaCount: 1

backend:
  image:
    tag: "dev-latest"
  hpa:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    LOG_LEVEL: "debug"
    NODE_ENV: "development"

frontend:
  image:
    tag: "dev-latest"

ingress:
  hosts:
    - host: dev.stackflow.example.com
