input {
  beats {
    port => 5044
  }
}

filter {
  if [service] == "stackflow-backend" {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "stackflow-logs-%{+YYYY.MM.dd}"
  }
}
