apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackflow-prod
  namespace: argocd
  labels:
    environment: prod
    strategy: blue-green
spec:
  project: default
  source:
    repoURL: https://github.com/Pradeepks01/StackFlow.git
    targetRevision: main
    path: helm/stackflow
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
